{% set name = "libgsf" %}
{% set version = "1.14.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ ".".join(version.split(".")[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 6e6c20d0778339069d583c0d63759d297e817ea10d0d897ebbe965f16e2e8e52

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libgsf", max_pin="x.x") }}

requirements:
  build:
    - perl *
    - perl-xml-parser
    - pkg-config
    - gnuconfig  # [unix]
    - make  # [unix]
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
    - zlib
    - bzip2
    - pcre
  run:
    - glib
    - libxml2
    - zlib
    - bzip2

test:
  commands:
    - gsf --help
    - gsf --version

about:
  home: https://github.com/GNOME/libgsf
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  license_url: https://github.com/GNOME/libgsf/blob/master/COPYING
  summary: The G Structured File Library
  description: |
    The project aims to provide an efficient extensible i/o abstraction
    for dealing with different structured file formats.
  doc_url: https://github.com/GNOME/libgsf
  doc_source_url: https://github.com/GNOME/libgsf/tree/master/doc
  dev_url: https://github.com/GNOME/libgsf

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - katietz
