{% set name = "libgsf" %}
{% set version = "1.14.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ ".".join(version.split(".")[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 6e6c20d0778339069d583c0d63759d297e817ea10d0d897ebbe965f16e2e8e52

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libgsf", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
    - make  # [unix]
    - perl *
    - perl-xml-parser
    - pkg-config
  host:
    - bzip2
    - glib
    - libxml2 {{ libxml2 }}
    - pcre 8.45
    - zlib 1.2.13
    - gettext  # [osx]
  run:
    - bzip2
    - glib
    - {{ pin_compatible('libxml2') }}
    - zlib >=1.2.13,<1.2.14

test:
  commands:
    - gsf --help
    - gsf --version

about:
  home: https://gitlab.gnome.org/GNOME/libgsf
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: The G Structured File Library
  description: |
    The project aims to provide an efficient extensible i/o abstraction
    for dealing with different structured file formats.
  doc_url: https://gitlab.gnome.org/GNOME/libgsf
  dev_url: https://gitlab.gnome.org/GNOME/libgsf

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - katietz
