{% set name = "libgsf" %}
{% set version = "1.14.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnome.org/pub/GNOME/sources/{{ name }}/1.14/{{ name }}-{{ version }}.tar.xz
  sha256: d188ebd3787b5375a8fd38ee6f761a2007de5e98fa0cf5623f271daa67ba774d

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libgsf", max_pin="x.x") }}

requirements:
  build:
    - perl
    - perl-xml-parser
    - pkg-config
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
    - zlib
    - bzip2
    - pcre
  run:
    - glib
    - libxml2
    - zlib
    - bzip2

test:
  commands:
    - gsf --help
    - gsf --version

about:
  home: https://github.com/GNOME/libgsf
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: An extensible I/O abstraction library for dealing with structured file formats

extra:
  recipe-maintainers:
    - sebastian-luna-valero
