travis:
  secure:
    BINSTAR_TOKEN: CPSBk9D0k4J0yKx2TRK6xHbkZ1aj5UQWWCOeJpB6regeboAdRQKQhXCsKqo3+/D1phg4ZAQ+h2Gk14TNEjiE3z3pzLc1Lc4YZlmasaE2YOBLpcBY/YPCuisV3OFGyF9HyxSNjT8DBOSEZJIZe3qNlzmqLDio+LqZZaqvTglwx/CR2EOQZWJK9KOvIB450sSHW9skP9Lh/QoQuddliCapOUVBiaC0fH5NFCG50r/hQUXBxBm6OUGZcOwoGusk3oM2s8WWo+uqrmDkeHFAQIalDhAEuiPw7MCrm5LgsvSEUwQyem80oXCSRliXCyX1cMrCGvJ+O7wIh4xbBJIyTTf2Hl+Zb0LrEGWe6l0wO70RTte6fdcOLAnW0WD/myHBdIm3yzOhfhK7buKQj4qaIeSAmbk4IfafDJwbqJ12Bo/Iu6b4SlGvBiIYrGiB09BoUZXZLYnfxKWRFjHhd7QzWgxK6SwDThdPvCPESVYZsRVGTbyQFqAUltCIIQRyc8zGsTE2np+wkK2vP6HlUEn5M/xfsCCHlepRIQ1rzdXU6F1QvDk3sz6LwENikfGEZceGGDQ+Zfnja7sMpBjMsWnjpAJUcsiNVbiqICkuqOwvu+yjQ4BWccz1eLqzqKAqvdYBNGEoOWEPqzFE+20a9h9jtk3tEEZcrn3BdWFBWbbsHS50Ip4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
